# BrandedReportPdf — RBPDF subclass that renders the plugin's reports with
# a consistent professional look: branded header/footer on every page, KPI
# tiles for the summary, and accent-line section headings.
#
# Usage:
#   pdf = BrandedReportPdf.new(report_title: title, project: @project,
#                              selected_year: @selected_year)
#   pdf.add_page
#   pdf.print_cover(generated_at: ...)
#   pdf.kpi_grid({ 'Total Items' => 42, 'Total Value' => 12_500_000 })
#   pdf.section_heading('Status Distribution')
#   pdf.data_table(['Status', 'Count'], rows)
#   ...
#   pdf.output
require 'rbpdf'

class BrandedReportPdf < RBPDF
  # Brand colors (RGB integers).
  ACCENT     = [107,  79, 199].freeze  # violet (#6B4FC7)
  INK        = [ 31,  35,  48].freeze  # near-black (#1F2330)
  MUTED      = [ 92, 101, 115].freeze  # muted gray (#5C6573)
  HAIRLINE   = [211, 215, 223].freeze  # light gray (#D3D7DF)
  HEADER_BG  = [244, 243, 249].freeze  # very light violet (#F4F3F9)
  ZEBRA_BG   = [250, 250, 251].freeze  # near-white (#FAFAFB)

  def initialize(report_title:, project: nil, selected_year: nil, **rbpdf_opts)
    super(**rbpdf_opts)
    @report_title  = report_title
    @project       = project
    @selected_year = selected_year

    set_creator 'Redmine Purchase Requests Plugin'
    set_author "#{User.current.name} (#{User.current.mail})"
    set_title  report_title
    set_subject report_title

    set_margins(18, 28, 18)
    set_header_margin(8)
    set_footer_margin(12)
    set_auto_page_break(true, 22)
  end

  # --- Page chrome ---------------------------------------------------

  def Header
    set_font('helvetica', 'B', 9)
    set_text_color(*ACCENT)
    cell(0, 6, @report_title, 0, 0, 'L')

    scope_text = []
    scope_text << @project.name if @project
    scope_text << (@selected_year.present? ? "Year #{@selected_year}" : 'All Years')
    set_font('helvetica', '', 9)
    set_text_color(*MUTED)
    cell(0, 6, scope_text.join('  ·  '), 0, 1, 'R')

    # accent rule under header
    set_draw_color(*ACCENT)
    set_line_width(0.4)
    line(get_margins['left'], get_y + 1, get_page_width - get_margins['right'], get_y + 1)
    set_y(get_y + 3)
  end

  def Footer
    set_y(-15)
    set_draw_color(*HAIRLINE)
    set_line_width(0.2)
    line(get_margins['left'], get_y, get_page_width - get_margins['right'], get_y)
    set_y(get_y + 2)

    set_font('helvetica', '', 8)
    set_text_color(*MUTED)
    timestamp = Time.now.strftime('%Y-%m-%d %H:%M')
    cell(0, 5, "Generated #{timestamp} · #{User.current.name}", 0, 0, 'L')
    cell(0, 5, "Page #{get_alias_num_page} of #{get_alias_nb_pages}", 0, 1, 'R')
  end

  # --- Cover block ---------------------------------------------------

  def print_cover(generated_at:, intro: nil)
    set_y(get_y + 4)

    # Big title
    set_font('helvetica', 'B', 22)
    set_text_color(*ACCENT)
    cell(0, 12, @report_title, 0, 1, 'L')

    # Accent rule under title
    set_draw_color(*ACCENT)
    set_line_width(1.0)
    line(get_margins['left'], get_y, get_margins['left'] + 50, get_y)
    set_y(get_y + 4)

    # Project line
    if @project
      set_font('helvetica', 'B', 12)
      set_text_color(*INK)
      cell(0, 7, "Project: #{@project.name}", 0, 1, 'L')
    end

    # Year scope tag
    set_font('helvetica', 'B', 10)
    set_text_color(*MUTED)
    scope_text = @selected_year.present? ? "Year #{@selected_year}" : 'All Years'
    cell(0, 6, "Scope: #{scope_text}", 0, 1, 'L')

    # Generated meta
    set_font('helvetica', '', 9)
    set_text_color(*MUTED)
    cell(0, 5, "Generated: #{generated_at.strftime('%B %d, %Y at %I:%M %p')}", 0, 1, 'L')
    cell(0, 5, "Generated by: #{User.current.name} (#{User.current.mail})", 0, 1, 'L')

    if intro
      ln(3)
      set_font('helvetica', '', 10)
      set_text_color(*INK)
      multi_cell(0, 5, intro)
    end

    ln(6)
  end

  # --- KPI tile grid -------------------------------------------------

  # Render up to 6 KPI tiles in a responsive grid.
  # `kpis` is an Array of [label, value] pairs OR a Hash.
  def kpi_grid(kpis)
    pairs = kpis.is_a?(Hash) ? kpis.to_a : kpis.to_a
    return if pairs.empty?

    # Page geometry
    usable_width = get_page_width - get_margins['left'] - get_margins['right']
    cols = pairs.size >= 4 ? 4 : pairs.size
    tile_w = usable_width / cols.to_f
    tile_h = 18

    start_x = get_margins['left']
    start_y = get_y
    pairs.each_with_index do |(label, value), idx|
      col = idx % cols
      row = idx / cols
      x = start_x + col * tile_w
      y = start_y + row * (tile_h + 3)

      set_xy(x, y)
      set_fill_color(*HEADER_BG)
      set_draw_color(*HAIRLINE)
      rect(x, y, tile_w - 2, tile_h, 'DF')

      # value (big, accent)
      set_xy(x + 3, y + 2)
      set_font('helvetica', 'B', 16)
      set_text_color(*ACCENT)
      cell(tile_w - 6, 8, format_value(value), 0, 1, 'L')

      # label (small, muted)
      set_xy(x + 3, y + 11)
      set_font('helvetica', '', 8)
      set_text_color(*MUTED)
      cell(tile_w - 6, 5, label.to_s, 0, 0, 'L')
    end
    rows_count = ((pairs.size - 1) / cols) + 1
    set_y(start_y + rows_count * (tile_h + 3) + 4)
  end

  # --- Section headings ---------------------------------------------

  def section_heading(text)
    ln(2)
    set_font('helvetica', 'B', 13)
    set_text_color(*INK)
    cell(0, 8, text, 0, 1, 'L')

    set_draw_color(*ACCENT)
    set_line_width(0.6)
    line(get_margins['left'], get_y - 1, get_margins['left'] + 18, get_y - 1)

    set_draw_color(*HAIRLINE)
    set_line_width(0.2)
    line(get_margins['left'] + 18, get_y - 1, get_page_width - get_margins['right'], get_y - 1)
    set_y(get_y + 2)
  end

  # --- Data tables ---------------------------------------------------

  # `header_row`: Array of column titles (Strings).
  # `data_rows`:  Array of Arrays of cell values.
  # `col_widths`: Optional Array of widths (in mm) that should sum to usable width.
  def data_table(header_row, data_rows, col_widths: nil)
    return if data_rows.nil? || data_rows.empty?

    usable_width = get_page_width - get_margins['left'] - get_margins['right']
    widths = col_widths || Array.new(header_row.size) { usable_width / header_row.size.to_f }

    row_h = 6

    # Header
    set_fill_color(*HEADER_BG)
    set_draw_color(*HAIRLINE)
    set_text_color(*ACCENT)
    set_font('helvetica', 'B', 9)
    header_row.each_with_index do |h, i|
      cell(widths[i], row_h + 1, h.to_s, 1, 0, 'L', true)
    end
    ln

    # Body
    set_font('helvetica', '', 9)
    set_text_color(*INK)
    data_rows.each_with_index do |row, idx|
      zebra = idx.odd?
      if zebra
        set_fill_color(*ZEBRA_BG)
      else
        set_fill_color(255, 255, 255)
      end
      check_page_break(row_h)
      row.each_with_index do |val, i|
        cell(widths[i], row_h, val.to_s, 1, 0, 'L', true)
      end
      ln
    end
    ln(2)
  end

  # --- Helpers -------------------------------------------------------

  def check_page_break(needed_height)
    if get_y + needed_height > get_page_height - get_break_margin
      add_page
    end
  end

  def format_value(value)
    return '—' if value.nil?
    return value.size.to_s if value.is_a?(Array)
    if value.is_a?(Numeric)
      if value.is_a?(Integer)
        value.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
      elsif value.abs >= 1_000_000
        "$#{(value / 1_000_000.0).round(2)}M"
      elsif value.abs >= 1_000
        "$#{(value / 1_000.0).round(1)}K"
      else
        ("%.2f" % value).to_s
      end
    else
      value.to_s
    end
  end
end
